package com.techphantoms.pocketqa.bridge

import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableMap
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.modules.core.DeviceEventManagerModule
import com.techphantoms.pocketqa.capture.CaptureCoordinator
import com.techphantoms.pocketqa.compiler.CompileCoordinator
import com.techphantoms.pocketqa.execution.ReplayExecutor
import com.techphantoms.pocketqa.explorer.ExplorerAgent
import com.techphantoms.pocketqa.export.ExportCoordinator
import com.techphantoms.pocketqa.inference.InferenceRouter
import com.techphantoms.pocketqa.policy.PolicyEngine
import com.techphantoms.pocketqa.spec.NativePocketQaModuleSpec
import com.techphantoms.pocketqa.storage.PocketQaRepository
import java.util.UUID

/**
 * PocketQaModule — TurboModule bridge between JS and the Kotlin coordinators.
 *
 * The abstract [NativePocketQaModuleSpec] is generated by React Native codegen
 * from `src/native/NativePocketQaModule.ts` at build time (`newArchEnabled=true`
 * in `gradle.properties`, plus the `codegenConfig` block in `package.json`).
 *
 * Every command below delegates to the coordinator that owns the concern in
 * Kotlin. The bridge only serialises/deserialises across the JSI boundary and
 * enforces the wire-safe error envelope declared in §11.3.
 */
@ReactModule(name = PocketQaModule.NAME)
class PocketQaModule(private val reactContext: ReactApplicationContext) :
    NativePocketQaModuleSpec(reactContext) {

    companion object { const val NAME: String = "PocketQaModule" }

    private val repo = PocketQaRepository(reactContext)
    private val policy = PolicyEngine()
    private val inference = InferenceRouter(reactContext)
    private val capture = CaptureCoordinator(reactContext, repo, policy)
    private val compiler = CompileCoordinator(repo, inference)
    private val executor = ReplayExecutor(reactContext, repo, policy)
    private val explorer = ExplorerAgent(reactContext, repo, policy, inference)
    private val export = ExportCoordinator(reactContext, repo)

    override fun getName(): String = NAME

    // NativeEventEmitter contract — required overrides for TurboModules that
    // want to emit events. addListener/removeListeners are no-ops because we
    // publish through RCTDeviceEventEmitter directly (see [emit] below).
    override fun addListener(eventName: String) { /* no-op */ }
    override fun removeListeners(count: Double) { /* no-op */ }

    fun emit(event: String, payload: WritableMap) {
        reactApplicationContext
            .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
            .emit(event, payload)
    }

    // ---- Envelope + guard ------------------------------------------------------

    /** Reject a promise with the wire-safe PocketQaError envelope (§11.3). */
    private fun rejectWithEnvelope(
        promise: Promise, code: String, message: String,
        recoverable: Boolean = true, remediation: String? = null,
    ) {
        val envelope = Arguments.createMap().apply {
            putString("code", code)
            putString("message", message)
            putBoolean("recoverable", recoverable)
            if (remediation != null) putString("remediation", remediation)
            putString("correlationId", UUID.randomUUID().toString())
        }
        promise.reject(code, message, envelope)
    }

    private inline fun guard(promise: Promise, block: () -> Unit) {
        try { block() }
        catch (e: com.techphantoms.pocketqa.OperationLock.ConflictingOperationException) {
            rejectWithEnvelope(promise, "OPERATION_IN_PROGRESS", e.message ?: "Another operation is running", true,
                "Wait for the active ${e.current.kind} to finish, or cancel it first.")
        }
        catch (e: SecurityException) { rejectWithEnvelope(promise, "POLICY_HARD_STOP", e.message ?: "Blocked by policy", false, e.message) }
        catch (e: IllegalStateException) { rejectWithEnvelope(promise, "INVALID_STATE", e.message ?: "Bad state", true, null) }
        catch (e: IllegalArgumentException) { rejectWithEnvelope(promise, "INVALID_INPUT", e.message ?: "Bad input", true, null) }
        catch (e: Throwable) { rejectWithEnvelope(promise, "UNEXPECTED", e.message ?: e::class.java.simpleName, true, null) }
    }

    // ---- Startup / readiness ---------------------------------------------------

    override fun getStartupState(promise: Promise) = guard(promise) { promise.resolve(repo.startupState()) }
    override fun getReadiness(promise: Promise) = guard(promise) { promise.resolve(repo.readiness()) }
    override fun openAccessibilitySettings(promise: Promise) = guard(promise) {
        capture.openAccessibilitySettings(); promise.resolve(null)
    }
    override fun listAllowlistedApps(promise: Promise) = guard(promise) { promise.resolve(policy.allowlist(reactContext)) }
    override fun setOfflineMode(offline: Boolean, promise: Promise) = guard(promise) {
        repo.setOfflineMode(offline); promise.resolve(null)
    }

    // ---- Consent + intent ------------------------------------------------------

    override fun recordConsent(promise: Promise) = guard(promise) { repo.recordConsent(); promise.resolve(null) }
    override fun createIntent(input: ReadableMap, promise: Promise) = guard(promise) { promise.resolve(repo.createIntent(input)) }

    // ---- Capture ---------------------------------------------------------------

    override fun startCapture(input: ReadableMap, promise: Promise) = guard(promise) { capture.start(input, promise) }
    override fun pauseCapture(id: String, promise: Promise) = guard(promise) { capture.pause(id); promise.resolve(null) }
    override fun resumeCapture(id: String, promise: Promise) = guard(promise) { capture.resume(id); promise.resolve(null) }
    override fun finishCapture(id: String, promise: Promise) = guard(promise) { capture.finish(id, compiler, promise) }
    override fun cancelCapture(id: String, del: Boolean, promise: Promise) = guard(promise) {
        capture.cancel(id, del); promise.resolve(null)
    }
    override fun simulateCaptureEvent(id: String, evt: ReadableMap, promise: Promise) = guard(promise) {
        capture.simulate(id, evt); promise.resolve(null)
    }

    // ---- Compile / draft -------------------------------------------------------

    override fun getCompileJob(id: String, promise: Promise) = guard(promise) { promise.resolve(compiler.job(id)) }
    override fun cancelAiEnhancement(id: String, promise: Promise) = guard(promise) { compiler.cancelAi(id); promise.resolve(null) }
    override fun getDraft(id: String, promise: Promise) = guard(promise) { promise.resolve(repo.draft(id)) }
    override fun saveDraft(req: ReadableMap, promise: Promise) = guard(promise) { promise.resolve(repo.saveDraft(req)) }
    override fun validateDraft(id: String, promise: Promise) = guard(promise) { promise.resolve(compiler.validate(id)) }
    override fun approveDraft(id: String, promise: Promise) = guard(promise) { promise.resolve(repo.approveDraft(id)) }

    // ---- Tests / runs / evidence -----------------------------------------------

    override fun listTests(promise: Promise) = guard(promise) { promise.resolve(repo.listTests()) }
    override fun getTest(id: String, version: Double, promise: Promise) = guard(promise) {
        promise.resolve(repo.getTest(id, version.toInt()))
    }
    override fun startReplay(id: String, version: Double, promise: Promise) = guard(promise) {
        executor.start(id, version.toInt(), promise)
    }
    override fun stopReplay(runId: String, promise: Promise) = guard(promise) { executor.stop(runId); promise.resolve(null) }
    override fun getRun(id: String, promise: Promise) = guard(promise) { promise.resolve(repo.run(id)) }
    override fun getEvidenceTimeline(id: String, promise: Promise) = guard(promise) { promise.resolve(repo.evidenceTimeline(id)) }
    override fun getState(stateId: String, promise: Promise) = guard(promise) { promise.resolve(repo.uiState(stateId)) }
    override fun listSelectorCandidates(draftId: String, stepId: String, promise: Promise) = guard(promise) {
        promise.resolve(repo.selectorCandidates(draftId, stepId))
    }
    override fun promoteFallbackSelector(draftId: String, stepId: String, candidateIndex: Double, promise: Promise) = guard(promise) {
        promise.resolve(repo.promoteFallback(draftId, stepId, candidateIndex.toInt()))
    }
    override fun getFailureProposal(runId: String, promise: Promise) = guard(promise) { promise.resolve(repo.failureProposal(runId)) }
    override fun submitVoiceTranscript(intentId: String, transcript: String, promise: Promise) = guard(promise) {
        promise.resolve(inference.transcribe(intentId, transcript))
    }
    override fun checkpointActiveOperation(promise: Promise) = guard(promise) {
        repo.checkpoint()
        // Rehydrate the JS layer too. CAPTURE_PROGRESS is only pushed when the
        // service observes a new stable state, so a screen that was backgrounded
        // during the demonstration comes back showing zero steps — and the Finish
        // button is disabled below two, which made a completed capture
        // un-finishable.
        capture.emitProgressFor(repo)
        promise.resolve(null)
    }

    // ---- Missions --------------------------------------------------------------

    override fun createMission(input: ReadableMap, promise: Promise) = guard(promise) { promise.resolve(repo.createMission(input)) }
    override fun approveAndStartMission(id: String, promise: Promise) = guard(promise) { explorer.start(id, promise) }
    override fun stopMission(id: String, promise: Promise) = guard(promise) { explorer.stop(id); promise.resolve(null) }
    override fun getMission(id: String, promise: Promise) = guard(promise) { promise.resolve(repo.mission(id)) }

    // ---- Export ----------------------------------------------------------------

    override fun exportTest(id: String, version: Double, promise: Promise) = guard(promise) { export.test(id, version.toInt(), promise) }
    override fun exportEvidence(id: String, promise: Promise) = guard(promise) { export.evidence(id, promise) }
    override fun shareArtifact(uri: String, mime: String, promise: Promise) = guard(promise) { export.share(uri, mime); promise.resolve(null) }
    override fun copyRedactedDiagnostics(id: String, promise: Promise) = guard(promise) { export.copyDiagnostics(id); promise.resolve(null) }

    // ---- Providers -------------------------------------------------------------

    override fun saveProviderCredential(input: ReadableMap, promise: Promise) = guard(promise) {
        promise.resolve(repo.saveProvider(input))
    }
    override fun deleteProviderCredential(provider: String, promise: Promise) = guard(promise) {
        repo.deleteProvider(provider); promise.resolve(null)
    }
    override fun deleteSession(id: String, promise: Promise) = guard(promise) { repo.deleteSession(id); promise.resolve(null) }
    override fun deleteTest(id: String, promise: Promise) = guard(promise) { repo.deleteTest(id); promise.resolve(null) }
    override fun deleteAllData(promise: Promise) = guard(promise) { repo.deleteAll(); promise.resolve(null) }
}
