import JSZip from "jszip";
import type { ApprovedTest, ReplayResult, UIState } from "./schemas";
import { toMaestroYaml } from "./maestro";
import { djb2 } from "./ids";

/**
 * Build a zippable evidence bundle — PRD FR-EVD-002.
 */
export interface EvidenceInput {
  test: ApprovedTest;
  result: ReplayResult;
  states: Record<string, UIState>;
  intent: string;
  device: { model: string; os: string; app: string; pocketqa: string };
  offline: boolean;
}

export async function buildEvidenceZip(input: EvidenceInput): Promise<Blob> {
  const zip = new JSZip();
  const testJson = JSON.stringify(input.test, null, 2);
  zip.file("test.json", testJson);
  zip.file("result.json", JSON.stringify(input.result, null, 2));
  zip.file("intent.txt", input.intent);
  zip.file("maestro.yaml", toMaestroYaml(input.test));

  const referencedStateIds = new Set<string>();
  for (const step of input.test.steps) {
    referencedStateIds.add(step.beforeStateId);
    referencedStateIds.add(step.afterStateId);
  }
  for (const stepRes of input.result.stepResults) {
    if (stepRes.beforeStateId) referencedStateIds.add(stepRes.beforeStateId);
    if (stepRes.afterStateId) referencedStateIds.add(stepRes.afterStateId);
  }

  const stateFolder = zip.folder("states")!;
  for (const id of referencedStateIds) {
    const state = input.states[id];
    if (!state) continue;
    stateFolder.file(`${id}.json`, JSON.stringify(state, null, 2));
  }

  const manifest = {
    schemaVersion: "pocketqa/evidence@1",
    generatedAt: new Date().toISOString(),
    intent: input.intent,
    testId: input.test.id,
    testVersion: input.test.version,
    device: input.device,
    executionPolicy: {
      allowlist: [input.test.packageName],
      offline: input.offline,
      connectedProvider: null,
    },
    result: {
      passed: input.result.passed,
      failure: input.result.failure ?? null,
      steps: input.result.stepResults.length,
      assertions: input.result.assertionResults.length,
    },
    integrity: {
      testHash: djb2(testJson),
      resultHash: djb2(JSON.stringify(input.result)),
    },
    notes: "Generated by PocketQA — sensitive fields redacted per policy.",
  };
  zip.file("manifest.json", JSON.stringify(manifest, null, 2));

  return await zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
