import { stringify } from "yaml";
import type { ApprovedTest, TestDraft, TestStep } from "./schemas";

/**
 * Maestro YAML exporter — PRD FR-EVD-004 / AT-11.
 *
 * We generate Maestro commands from PocketQA's normalized steps.  Selectors
 * are translated using the ranked strategy:
 *   testId       -> id: "value"
 *   resourceId   -> id: "value"
 *   accessibilityLabel -> text: "value"  (accessibility label maps to displayed
 *                                         label in Maestro's text matcher)
 *   textAndRole  -> text: "value"
 *   coordinates  -> not emitted (fails export with a clear reason)
 */

export function toMaestroYaml(test: TestDraft | ApprovedTest): string {
  const commands: unknown[] = [
    { launchApp: test.packageName },
  ];

  for (const step of test.steps) {
    commands.push(...emitStep(step));
  }

  for (const a of test.finalAssertions) {
    if (a.kind === "textVisible") commands.push({ assertVisible: a.target });
    else if (a.kind === "textAbsent") commands.push({ assertNotVisible: a.target });
  }

  const flow = {
    appId: test.packageName,
    name: test.name,
    tags: ["pocketqa", "regression"],
  };

  const header = stringify(flow).trimEnd();
  const body = stringify(commands).trimEnd();
  return `# Generated by PocketQA (deterministic exporter)\n# Intent: ${test.intent}\n${header}\n---\n${body}\n`;
}

function emitStep(step: TestStep): unknown[] {
  const out: unknown[] = [];
  const matcher = step.selector ? selectorToMatcher(step.selector.primary) : null;

  switch (step.action) {
    case "tap":
    case "longPress":
      if (matcher) out.push({ tapOn: matcher });
      break;
    case "typeText":
      if (matcher) out.push({ tapOn: matcher });
      if (step.input !== undefined) out.push({ inputText: step.input });
      break;
    case "clearText":
      if (matcher) out.push({ tapOn: matcher }, { eraseText: 50 });
      break;
    case "back":
      out.push({ back: true });
      break;
    case "wait":
      out.push({ extendedWaitUntil: { visible: { text: step.label }, timeout: step.waitMs ?? 500 } });
      break;
    case "scroll":
      out.push({ scroll: true });
      break;
    case "launch":
      // handled at the top of the flow
      break;
    case "unknown":
      // never approved without correction; export as a comment marker
      out.push({ evalScript: `\n// unresolved step: ${step.label}\n` });
      break;
  }

  for (const a of step.assertions) {
    if (a.kind === "textVisible") out.push({ assertVisible: a.target });
    else if (a.kind === "textAbsent") out.push({ assertNotVisible: a.target });
  }
  return out;
}

function selectorToMatcher(sel: { strategy: string; value: string }): Record<string, string> | null {
  switch (sel.strategy) {
    case "testId":
    case "resourceId":
      return { id: sel.value };
    case "accessibilityLabel":
    case "textAndRole":
      return { text: sel.value };
    case "roleAndRelation":
      return { text: sel.value };
    case "relativePosition":
      return { id: sel.value };
    case "coordinates":
      return null; // fail-safe: don't emit brittle taps
  }
  return null;
}
