import type { ApprovedTest, ReplayResult, UIState } from "./schemas";
import { toMaestroYaml } from "./maestro";
import { djb2 } from "./ids";

/**
 * Serialize an evidence bundle to a plain payload.  The React Native façade
 * hands this to the native side (`PocketQaNative.exportEvidence`) which is
 * responsible for writing it to app-private storage and returning a
 * shareable `content://` URI.  Nothing here touches the DOM/Blob API.
 */

export interface EvidenceInput {
  test: ApprovedTest;
  result: ReplayResult;
  states: Record<string, UIState>;
  intent: string;
  device: { model: string; os: string; app: string; pocketqa: string };
  offline: boolean;
}

export interface EvidencePayload {
  files: Array<{ path: string; content: string; contentType: "json" | "yaml" | "text" }>;
  manifest: EvidenceManifest;
}

export interface EvidenceManifest {
  schemaVersion: "pocketqa/evidence@1";
  generatedAt: string;
  intent: string;
  testId: string;
  testVersion: number;
  device: EvidenceInput["device"];
  executionPolicy: {
    allowlist: string[];
    offline: boolean;
    connectedProvider: string | null;
  };
  result: {
    passed: boolean;
    failure: NonNullable<ReplayResult["failure"]> | null;
    steps: number;
    assertions: number;
  };
  integrity: {
    testHash: string;
    resultHash: string;
  };
  notes: string;
}

export function buildEvidencePayload(input: EvidenceInput): EvidencePayload {
  const files: EvidencePayload["files"] = [];
  const testJson = JSON.stringify(input.test, null, 2);
  files.push({ path: "test.json", content: testJson, contentType: "json" });
  files.push({ path: "result.json", content: JSON.stringify(input.result, null, 2), contentType: "json" });
  files.push({ path: "intent.txt", content: input.intent, contentType: "text" });
  files.push({ path: "maestro.yaml", content: toMaestroYaml(input.test), contentType: "yaml" });

  const referenced = new Set<string>();
  for (const step of input.test.steps) {
    referenced.add(step.beforeStateId);
    referenced.add(step.afterStateId);
  }
  for (const stepRes of input.result.stepResults) {
    if (stepRes.beforeStateId) referenced.add(stepRes.beforeStateId);
    if (stepRes.afterStateId) referenced.add(stepRes.afterStateId);
  }
  for (const id of referenced) {
    const state = input.states[id];
    if (!state) continue;
    files.push({ path: `states/${id}.json`, content: JSON.stringify(state, null, 2), contentType: "json" });
  }

  const manifest: EvidenceManifest = {
    schemaVersion: "pocketqa/evidence@1",
    generatedAt: new Date().toISOString(),
    intent: input.intent,
    testId: input.test.id,
    testVersion: input.test.version,
    device: input.device,
    executionPolicy: {
      allowlist: [input.test.packageName],
      offline: input.offline,
      connectedProvider: null,
    },
    result: {
      passed: input.result.passed,
      failure: input.result.failure ?? null,
      steps: input.result.stepResults.length,
      assertions: input.result.assertionResults.length,
    },
    integrity: {
      testHash: djb2(testJson),
      resultHash: djb2(JSON.stringify(input.result)),
    },
    notes: "Generated by PocketQA — sensitive fields redacted per policy.",
  };
  files.push({ path: "manifest.json", content: JSON.stringify(manifest, null, 2), contentType: "json" });
  return { files, manifest };
}
